navikt/familie-ef-minside-frontend

.github/workflows/build_n_deploy_dev.yaml
=> Fjerner test-ci for build and deploy i dev

README.md, server/decorator.ts
Vil ikke ha "enkel" dekoratør på min side
=> Vil ikke bruke "simple" dekoratør

config/webpack.build.js, package-lock.json, package.json, server/csp.js, server/decorator.js, server/decorator.ts, server/logger.js, server/miljø.js, server/miljø.ts, server/package-lock.json, server/package.json, server/proxy.js, server/proxy.ts, server/routes.js, server/routes.ts, server/server.js, server/server.ts, server/tokenProxy.js, server/tokenProxy.ts, server/tokenx.js, server/tokenx.ts, src/App.tsx, src/api/axios.ts, src/api/env.ts, src/context/AppContext.tsx, src/pages/Forside.tsx
=> Legge til lenker

src/components/LenkePanelLiten.tsx, src/components/LenkePanelMikro.tsx, src/components/LenkePanelStor.tsx, src/components/SideTittel.tsx, src/pages/Forside/Forside.tsx, src/pages/Forside/LenkePanelLitenListe.tsx, src/pages/Forside/LenkePanelStorListe.tsx, src/pages/Forside/SnarveierLitenSkjerm.tsx, src/pages/Forside/SnarveierStorSkjerm.tsx
=> Universal utforming

src/pages/Forside/Snarveier.tsx
=> fix: import var feil i Snarveier.tsx

.github/workflows/build_n_deploy_prod.yaml, src/pages/Forside/LenkePanelStorListe.tsx
=> Deploy ved push til main

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .github/workflows/codeql.yml
=> bumper actions for nais/deploy og codeql

.github/workflows/codeql.yml, server/package-lock.json, server/package.json
=> bumpet minor patch dependencies i server. Bumpet codequl actions

server/package-lock.json, server/package.json, src/amplitude/amplitude.ts
=> bumper jsdom til ny major

nais-dev.yaml, nais-prod.yaml
=> oppdaterer nais.yaml-filer slik at de blir gyldige

server/decorator.ts, src/components/LenkePanelMikro.tsx
=> forkorter tekst i breadcrumb

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-17677)
=> Vil deploye uten secrets.NAIS_DEPLOY_APIKEY.

README.md, server/miljø.ts, server/routes.ts, server/tokenProxy.ts, src/api/env.ts, src/context/AppContext.tsx, src/hooks/useHentPersonData.ts
=> skal støtte lokal kjøring mot lokal backend (søknad-api)

server/decorator.ts, server/miljø.ts, server/routes.ts, server/server-lokal.ts, src/App.tsx, src/api/env.ts, src/components/LenkePanelStor.tsx, src/components/UnorderedList.tsx, src/pages/Dokumentoversikt/Dokument.tsx, src/pages/Dokumentoversikt/DokumentListe.tsx, src/pages/Dokumentoversikt/Dokumentoversikt.tsx, src/pages/Dokumentoversikt/Vedlegg.tsx, src/pages/Dokumentoversikt/VedleggListe.tsx, src/pages/Forside/DineDokumenter.tsx, src/pages/Forside/Forside.tsx, src/utils/scrollEffect.ts
Utbedringer relatert til lansering av dokumentvisning på minside. Utbedringene kan leses utfra commit-navnene.
Testet i preprod ✅
=> Dokumentoversikt utbedringer

server/tokenProxy.ts
Implementerer derfor at minside skal hente token fra fakedings ved lokal kjøring.
=> Søknad-api validerer nå mot fakedings ved lokal kjøring etter oppgradering til token-support v4

src/pages/Stønadoversikt/StønadTabellAvansert.tsx, src/pages/Stønadoversikt/utils.ts
Må opplyse bruker om hvorfor det kommer "nye rader" 1. mai hvert år.
=> Skal ha info om grunnbeløp over overgangsstønadstabellen

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, nais-dev.yaml
GHCR ga problemer med håndtering av image, og nais-teamet jobbet derfor med alternativ løsning. Løsningen ble GAR og det er dermed anbefalt å migrere over for en bedre brukeropplevelse.
https://nav-it.slack.com/archives/C5KUST8N6/p1678189735336849?thread_ts=1678188149.218519&cid=C5KUST8N6
https://docs.nais.io/build/how-to/oci-migration/
Skal squashes før merge ja 🙈
=> Migrere til GAR

package-lock.json, package.json, server/package-lock.json, server/package.json, server/proxy.ts, server/routes.ts
=> bumper http-proxy-middleware til ny major

package-lock.json, package.json
=> Oppdaterer majsor Vitest

.github/dependabot.yml
=> Ønsker at dependabot skal ta med oppdateringer på semver-patch i PR.

package-lock.json, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/pages/Dokumentoversikt/utils.test.ts
=> Endre fra NAV til Nav på minside

src/language/tekster_en.ts, src/language/tekster_nb.ts, src/pages/Dokumentoversikt/Dokumentoversikt.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-23610)
=> Fix breadcrumb og tekster på dokumentoversikt

server/miljø.ts, src/api/env.ts, src/language/tekster_en.ts, src/language/tekster_nb.ts, src/pages/Forside/Snarveier.tsx
[Favro](https://favro.com/organization/98c34fb974ce445eac854de0/a64c6aad9b0d61ef6c0290bd?card=NAV-22971)
=> Skal lenke til klage

package-lock.json, package.json, src/amplitude/amplitude.ts
=> Skal bruke Amplitude fra dekoratøren.

CODEOWNERS
=> endre codeowners til enslig-forsorger

.github/workflows/build_dev.yaml, .github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .github/workflows/codeql.yml, .github/workflows/removeOldImages.yaml
=> Skal pinne actions til spesifikke versjoner.

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml, .nais/app-dev.yaml, .nais/app-prod.yaml
- Legger til logging elastic og loki.
- Endrer struktur på nais filer
=> Observability + struktur nais filer

.github/dependabot.yml
=> Oppdaterer dependabot slik at bumping av actions også blir samlet i PR.
